### ISSUE TITLE
Completing all default Taps

### ISSUE THREAD

**Issue by dirathea** [dirathea/pipelinewise-operator#2]
Currently, the supported tap is very limited. This operator should be able to handle at least all the default taps out of the box.

**Comment by martinmalek** [comment]
Can I upvote Github and Jira as the first taps to be considered? Thanks.

**Comment by dirathea** [comment]
Yup! I think I'll finish all the tap this month

**Comment by dirathea** [comment]
Hi @martinmalek, I've updated this Operator to support all the taps that available on Pipelinewise.
I'll close this issue for now. Feel free to raise another issue about the taps.

**Comment by martinmalek** [comment]
Wonderful. Thanks for fixing.
